journal/app/urls.py
from django.contrib import admin
from django.urls import path
import app.views as app_views

app_name = 'journal'

urlpatterns = [
    path('', app_views.base, name='base'),
    path('users/',
         app_views.UsersListView.as_view(),
         name='user_list'
    ),
    path('posts/',
         app_views.PostsListView.as_view(),
         name='post_list'
    ),
    path('users/<int:pk>/',
         app_views.UserDetailView.as_view(),
         name='user_detail'
    ),
    path('posts/<int:pk>/',
         app_views.PostDetailView.as_view(),
         name='post_detail'
    ),
    path('users/create/',
         app_views.AddUserCreateView.as_view(),
         name='user_create'
    ),
    path('posts/create/',
         app_views.AddPostCreateView.as_view(),
         name='post_create'
    ),
]

journal/journal/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'journal'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='journal')),
]

journal/app/models.py
from django.db import models


class User(models.Model):
    username = models.CharField(max_length=200, null=False, unique=True)
    name = models.CharField(max_length=400, null=True)
    email = models.CharField(max_length=50, null=False, unique=True)

    def __str__(self):
        return f'{self.username}'


class Post(models.Model):
    title = models.CharField(max_length=200, null=False)
    body = models.TextField(null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.title}" by {self.user}'

journal/journal/journal/models.py
from django.db import models

# Create your models here.

journal/app/views.py
from django.shortcuts import render
from app.models import User, Post
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView


def base(request):
    return render(request, 'app/base.html')


class UsersListView(ListView):
    model = User
    template_name = 'app/user_list.html'
    context_object_name = 'users'


class UserDetailView(DetailView):
    model = User
    context_object_name = 'user'


class AddUserCreateView(CreateView):
    model = User
    success_url = reverse_lazy('journal:user_list')
    fields = ('name', 'username', 'email')


class PostDetailView(DetailView):
    model = Post
    context_object_name = 'post'


class PostsListView(ListView):
    model = Post
    template_name = 'app/post_list.html'
    context_object_name = 'posts'

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.select_related('user').all()
        return qs


class AddPostCreateView(CreateView):
    model = Post
    success_url = reverse_lazy('journal:post_list')
    fields = ('title', 'user', 'body')

journal/journal/journal/views.py
from django.shortcuts import render

# Create your views here.

journal/app/templates/app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block content %}
            Journal
        {% endblock %}
    </title>
<style>
   hr {
    border: none;
    background-color: black;
    height: 0.5px;
   }
  </style>
</head>
<body>
    <div class="main_container" >
        <div>
        {% block body %}
            <h2>Journal</h2>
        {% endblock %}
        </div>
    </div>
    <hr>
    <ul>
        <li>
            <a href="/">Main</a>
        </li>
        <li>
            <a href="/users/">Users</a>
        </li>
        <li>
            <a href="/posts/">Posts</a>
        </li>

    </ul>

</body>

</html>

journal/app/templates/app/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block content %}
             {{ post.title }}
        {% endblock %}
    </title>
<body>
    <div> {{ post.body }} </div>
    <h3> by {{ post.user }}</h3>
    <a href="{% url 'journal:post_list' %}">Back</a>
</body>

journal/app/templates/app/post_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        Add new post
    </title>
<body>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
</body>

journal/app/templates/app/post_list.html
{% extends "app/base.html" %}

{% block content %}
    Posts page
{% endblock %}
{% block body %}

<div class="h4"> Posts </div>
    {% for post in posts %}
        <ul>
            <li> <a href="{% url 'journal:post_detail' post.id %}">{{ post.title }}</a> </li>
        </ul>
    {% endfor %}
    <li>
        <a href="{% url 'journal:post_create' %}" class="btn">Create new post</a>
    </li>
{% endblock %}

journal/app/templates/app/user_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
         {{ user.username }}
    </title>
<body>
    <ul>
        <li>name {{ user.name }}  </li>
        <li>email {{ user.email }} </li>
        <a href="{% url 'journal:user_list' %}">Back</a>
    </ul>
</body>

journal/app/templates/app/user_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        Add new user
    </title>
<body>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
</body>

journal/app/templates/app/user_list.html
{% extends "app/base.html" %}

{% block content %}
    Users page
{% endblock %}
{% block body %}

<div class="h4"> Users </div>
    {% for user in users %}
    <ul>
      <li><a href="{% url 'journal:user_detail' user.id %}">{{ user.username }} ({{user.email}})</a></li>
    </ul>
    {% endfor %}
    <li>
        <a href="{% url 'journal:user_create' %}" class="btn">Create new user</a>
    </li>

{% endblock %}